all: client.c  monitor.c serverM.c serverA.c serverB.c serverC.c
		gcc -o client client.c
		gcc -o monitor monitor.c
		gcc -o serverM serverM.c
		gcc -o serverA serverA.c
		gcc -o serverB serverB.c
		gcc -o serverC serverC.c


serverM:
		./serverM

serverA:
		./serverA

serverB:
		./serverB

serverC:
		./serverC
